### ISSUE TITLE
Неочікувана помилка

### ISSUE THREAD

**Issue by balbulator** [PaulAnnekov/uasiren#1]
UKR
Перш за все хочу подякувати за таку потрібну в нашій країні інтеграцію.
Сьогодні я помітив, що датчики стали неактивними. Після якої події або оновлення я не зауважив.
В "Пристроях та сервісах" інтеграція стала червоною з вказанням помилки, але я не запам'ятав якої, щось пов'язане з API.
Спробував видалити і знов встановити інтеграцію, але тепер виникає помилка "Ukraine Alarm - Неочікувана помилка", відповідно інтеграція не встановлюється. 
В журналі помилок наступне:
Logger: homeassistant.components.ukraine_alarm.config_flow
Source: components/ukraine_alarm/config_flow.py:61
Integration: Ukraine Alarm (documentation, issues)
First occurred: 23:27:32 (2 occurrences)
Last logged: 23:34:37

Failed to connect to the service: 401, message='Unauthorized', url=URL('https://siren.pp.ua/api/v3/regions')

Буду дуже вдячний за допомогу.

ENG
First of all, I want to thank you for the integration that is so necessary in our country.
Today I noticed that the sensors have become inactive. After which event or update I did not notice.
In "Devices and services" the integration turned red with an error, but I don't remember which one, something related to the API.
I tried to remove and reinstall the integration, but now the error "Ukraine Alarm - Unexpected error" appears, so the integration is not installed.
The following is in the error log:
Logger: homeassistant.components.ukraine_alarm.config_flow
Source: components/ukraine_alarm/config_flow.py:61
Integration: Ukraine Alarm (documentation, issues)
First occurred: 23:27:32 (2 occurrences)
Last logged: 23:34:37

Failed to connect to the service: 401, message='Unauthorized', url=URL('https://siren.pp.ua/api/v3/regions')

I will be very grateful for your help.

**Comment by PaulAnnekov** [comment]
https://github.com/home-assistant/core/issues/75093
