### ISSUE TITLE
Приложение «Повітряна тривога» научилось предупреждать о химической и радиационной опасности

### ISSUE THREAD

**Issue by ntguest** [PaulAnnekov/uasiren#2]
https://itc.ua/news/prilozhenie-vozdushnaya-trevoga-nauchilos-preduprezhdat-o-himicheskoj-i-radiatsionnoj-opasnosti/

**Comment by PaulAnnekov** [comment]
У цій бібліотеці нічого змінювати не треба. Це у HA потрібно додати підтримку. Зроблю.

**Comment by PaulAnnekov** [comment]
https://github.com/home-assistant/core/pull/76155
