### ISSUE TITLE
Не працює інтеграція

### ISSUE THREAD

**Issue by zelin-sky** [PaulAnnekov/uasiren#5]
Вже доданий регіон не оновлює стан тривоги.
Неможливо додати новий регіон, видає помилку: "Не вдалося під'єднатися"
![Screenshot_20241029_221122_Home Assistant](https://github.com/user-attachments/assets/8e5da2e0-0e56-455b-a845-e9a0c1b3fc0d)

**Comment by PaulAnnekov** [comment]
Закінчилось місце на сервері із-за купи логів :(. Почистив, налаштував краще logrotate, додав собі алерт якщо місце буде закінчуватись. Все знову працює і більше повторюватись не повинно.
